### PR TITLE
Publish planning scene while planning

### LINKED ISSUE #3688: Updating rviz planning scene when monitored planning scene is locked
### Description

**General description:**

I'm not sure if we're configuring moveit and rviz slightly wrong, or if this is an actual problem.

We are setting up rviz with `Planning Scene Topic: /move_group/monitored_planning_scene` to display the robot.

We are planning and executing a series of motions, with planning and executing happening in parallel.

When a motion is executing while another motion is planning, the rviz visual of the robot freezes. This happens both when using a real robot, or using a simulated robot entirely run by moveit.

**Technical details:**

I have tracked the problem back to `PlanningSceneMonitor::scenePublishingThread`, where the `scene_update_mutex_` is locked while planning is happening. This blocks the publishing of the planning scene on `/move_group/monitored_planning_scene`.

**Possible solutions:**

 - Are we just hooking rviz up to the wrong planning scene? Is there a planning scene topic which is continuously updated, even when the monitored planning scene is locked?
 - If not, is the right solution to change how the planning scene monitor works, to have one planning scene which is continually updated, and a second planning scene which is locked when planning?

### Your environment
* ROS Distro: Noetic
* OS Version: e.g. Ubuntu 22.04
* Source or Binary build? Source
* If binary, which release version?
* If source, which branch? 1.1.16-b71e5f5ce5a9b3080dbcbb8d2e5d19cf5010e613

### Steps to reproduce
Plan and execute a series of motions, where the planning for subsequent motions happens while previous motions are executing.

### Expected behaviour
The rviz visualisation of the robot should follow the executing motion.

### Actual behaviour
The rviz visualisation freezes when a motion starts planning.

### Backtrace or Console output

Use [gist.github.com](gist.github.com) to copy-paste the console output or segfault backtrace using gdb.

### PR DESCRIPTION
**Pull request by rr-mark**
### Description

 - Fixes #3688
 - Adds `PlanningSceneMonitor::copyPlanningScene` and `ExecutableMotionPlan::copyPlanningScene` which return a copy of the planning scene.
 - Replaces a number of calls to `LockedPlanningSceneRO` with `copyPlanningScene`, to avoid locking the planning scene monitor during long operations.

### Checklist
- [ ] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [ ] Extend the tutorials / documentation [reference](http://moveit.ros.org/documentation/contributing/)
- [ ] Document API changes relevant to the user in the [MIGRATION.md](https://github.com/moveit/moveit/blob/master/MIGRATION.md) notes
- [ ] Create tests, which fail without this PR [reference](https://moveit.github.io/moveit_tutorials/doc/tests/tests_tutorial.html)
- [ ] Include a screenshot if changing a GUI
- [ ] While waiting for someone to review your request, please help review [another open pull request](https://github.com/moveit/moveit/pulls) to support the maintainers

[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!"

### CODE REVIEW

File: moveit_ros/planning/plan_execution/src/plan_execution.cpp [hunk 1]
```diff
@@ -107,28 +107,15 @@ void plan_execution::PlanExecution::stop()
...
-                                                                                      // not modify the world
-                                                                                      // representation while diff() is
-                                                                                      // called
-      plan.planning_scene_ = lscene->diff(scene_diff);
-    }
-    planAndExecuteHelper(plan, opt);
-  }
+  plan.planning_scene_monitor_ = planning_scene_monitor_;
+  plan.planning_scene_ = planning_scene_monitor_->copyPlanningScene(scene_diff);
+  planAndExecute(plan, opt);
```
Comment (rhaschke) [inline moveit_ros/planning/plan_execution/src/plan_execution.cpp:118]: Shouldn't this call `planAndExecuteHelper`? Otherwise, both methods call each other recursively forever.
```suggestion
  planAndExecuteHelper(plan, opt);
```

File: moveit_ros/planning/planning_scene_monitor/include/moveit/planning_scene_monitor/planning_scene_monitor.h [hunk 2]
```diff
@@ -591,6 +595,31 @@ class PlanningSceneMonitor : private boost::noncopyable
...
+  {
+    if (read_only_)
+      planning_scene_monitor_->unlockSceneRead();
+    else
+      planning_scene_monitor_->unlockSceneWrite();
+  }
+  PlanningSceneMonitor* planning_scene_monitor_;
+  bool read_only_;
+};
+
```
Comment (rhaschke) [inline moveit_ros/planning/planning_scene_monitor/include/moveit/planning_scene_monitor/planning_scene_monitor.h:622]: Why do we need to change the visibility of `SingleUnlock`? Can this be avoided?

File: moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp [hunk 3]
```diff
@@ -181,6 +181,19 @@ PlanningSceneMonitor::~PlanningSceneMonitor()
   rm_loader_.reset();
 }
 
+planning_scene::PlanningScenePtr PlanningSceneMonitor::copyPlanningScene(const moveit_msgs::PlanningScene& diff)
+{
+  planning_scene::PlanningScenePtr scene;
+  {
+    SingleUnlock lock(this, true);
+    scene = getPlanningScene()->diff();
```
Comment (rhaschke) [inline moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp:189]: Shouldn't this suffice:
```suggestion
    scene = LockedPlanningSceneRO(this)->diff();
```

**Review by rhaschke — COMMENTED** [review]
This points into the right direction. I'm sure there are many more PS locks.
Question: Do we still need `ExecutableMotionPlan::planning_scene_monitor_` after all?

**Comment by rr-mark** [comment]
From poking around the code, I think I probably have misunderstood `ExecutableMotionPlan`.

I assumed the `planning_scene_` member was supposed to be frozen when the class was made, but it looks like it's only supposed to be frozen when the planning scene is locked?

So I wonder if I should keep the `planning_scene_monitor_` variable, but remove the `planning_scene_` variable (in favour of calling `copyPlanningScene` as required)?

**Comment by rr-mark** [comment]
(This PR now solves the original problem - now I need to stop it breaking everything else)

**Comment by rhaschke** [comment]
> I assumed the `planning_scene_` member was supposed to be frozen when the class was made, but it looks like it's only supposed to be frozen when the planning scene is locked?

I don't know the used of it by heart and would need to dive into the code. Unfortunately, I don't have time to do that before the weekend.

**Comment by rr-mark** [comment]
I think my attempted changes to `plan_execution.cpp` are unworkable: the workflow seems to require that `plan.planning_scene_` be modified with `diff(scene_diff)` but still updated by the planning scene monitor.

I think I'm going to remove those changes, and limit the scope of this PR to the other places where `ExecutableMotionPlan` is used.

**Comment by rr-mark** [comment]
This approach doesn't seem to be working. I'm testing it by planning a series of motions, with subsequent motions planning while earlier motions are executing.

The first motion plans and executes fine, but later motions start printing "Returning dirty link transforms", and occasionally spurious collisions are reported. Then the move group node crashes with backtrace

```
0x00007de5ab7ea576 in Eigen::internal::transform_transform_product_impl<Eigen::Transform<double, 3, 1, 0>, Eigen::Transform<double, 3, 1, 0>, false>::run(Eigen::Transform<double, 3, 1, 0> const&, Eigen::Transform<double, 3, 1, 0> const&) () from /opt/ros/noetic/lib/libmoveit_planning_scene_monitor.so.1.1.16
(gdb) bt
#0  0x00007de5ab7ea576 in Eigen::internal::transform_transform_product_impl<Eigen::Transform<double, 3, 1, 0>, Eigen::Transform<double, 3, 1, 0>, false>::run(Eigen::Transform<double, 3, 1, 0> const&, Eigen::Transform<double, 3, 1, 0> const&) () from /opt/ros/noetic/lib/libmoveit_planning_scene_monitor.so.1.1.16
#1  0x00007de5aadc765f in moveit::core::AttachedBody::computeTransform(Eigen::Transform<double, 3, 1, 0> const&) () from /opt/ros/noetic/lib/libmoveit_robot_state.so.1.1.16
#2  0x00007de5aadea75c in moveit::core::RobotState::attachBody(std::unique_ptr<moveit::core::AttachedBody, std::default_delete<moveit::core::AttachedBody> >) ()
   from /opt/ros/noetic/lib/libmoveit_robot_state.so.1.1.16
#3  0x00007de5aadeabab in moveit::core::RobotState::copyFrom(moveit::core::RobotState const&) () from /opt/ros/noetic/lib/libmoveit_robot_state.so.1.1.16
#4  0x00007de5aadead68 in moveit::core::RobotState::RobotState(moveit::core::RobotState const&) () from /opt/ros/noetic/lib/libmoveit_robot_state.so.1.1.16
#5  0x00007de5aaa082c8 in planning_scene::PlanningScene::getCurrentStateNonConst() () from /opt/ros/noetic/lib/libmoveit_planning_scene.so.1.1.16
#6  0x00007de5a12ca235 in pilz_industrial_motion_planner::TrajectoryGenerator::MotionPlanInfo::MotionPlanInfo(std::shared_ptr<planning_scene::PlanningScene const> const&, moveit_msgs::MotionPlanRequest_<std::allocator<void> > const&) () from /opt/ros/noetic/lib/libplanning_context_loader_circ.so
#7  0x00007de5a12ca8f6 in pilz_industrial_motion_planner::TrajectoryGenerator::generate(std::shared_ptr<planning_scene::PlanningScene const> const&, moveit_msgs::MotionPlanRequest_<std::allocator<void> > const&, planning_interface::MotionPlanResponse&, double) () from /opt/ros/noetic/lib/libplanning_context_loader_circ.so
#8  0x00007de5a127015f in pilz_industrial_motion_planner::PlanningContextBase<pilz_industrial_motion_planner::TrajectoryGeneratorLIN>::solve(planning_interface::MotionPlanResponse&)
    () from /opt/ros/noetic/lib/libplanning_context_loader_lin.so
#9  0x00007de5aa28575f in boost::detail::function::function_obj_invoker3<planning_request_adapter::PlanningRequestAdapterChain::adaptAndPlan(std::shared_ptr<planning_interface::PlannerManager> const&, std::shared_ptr<planning_scene::PlanningScene const> const&, moveit_msgs::MotionPlanRequest_<std::allocator<void> > const&, planning_interface::MotionPlanResponse&, std::vector<unsigned long, std::allocator<unsigned long> >&) const::{lambda(std::shared_ptr<planning_scene::PlanningScene const> const&, moveit_msgs::MotionPlanRequest_<std::allocator<void> > const&, planning_interface::MotionPlanResponse&)#1}, bool, std::shared_ptr<planning_scene::PlanningScene const> const&, moveit_msgs::MotionPlanRequest_<std::allocator<void> > const&, planning_interface::MotionPlanResponse&>::invoke(boost::detail::function::function_buffer&, std::shared_ptr<planning_scene::PlanningScene const> const&, moveit_msgs::MotionPlanReq--Type <RET> for more, q to quit, c to continue without paging--
uest_<std::allocator<void> > const&, planning_interface::MotionPlanResponse&) () from /opt/ros/noetic/lib/libmoveit_planning_request_adapter.so.1.1.16
#10 0x00007de5a1caae6c in default_planner_request_adapters::FixWorkspaceBounds::adaptAndPlan(boost::function<bool (std::shared_ptr<planning_scene::PlanningScene const> const&, moveit_msgs::MotionPlanRequest_<std::allocator<void> > const&, planning_interface::MotionPlanResponse&)> const&, std::shared_ptr<planning_scene::PlanningScene const> const&, moveit_msgs::MotionPlanRequest_<std::allocator<void> > const&, planning_interface::MotionPlanResponse&, std::vector<unsigned long, std::allocator<unsigned long> >&) const ()
   from /opt/ros/noetic/lib/libmoveit_default_planning_request_adapter_plugins.so
#11 0x00007de5aa285983 in planning_request_adapter::(anonymous namespace)::callAdapter(planning_request_adapter::PlanningRequestAdapter const&, boost::function<bool (std::shared_ptr<planning_scene::PlanningScene const> const&, moveit_msgs::MotionPlanRequest_<std::allocator<void> > const&, planning_interface::MotionPlanResponse&)> const&, std::shared_ptr<planning_scene::PlanningScene const> const&, moveit_msgs::MotionPlanRequest_<std::allocator<void> > const&, planning_interface::MotionPlanResponse&, std::vector<unsigned long, std::allocator<unsigned long> >&) () from /opt/ros/noetic/lib/libmoveit_planning_request_adapter.so.1.1.16
#12 0x00007de5aa286b17 in planning_request_adapter::PlanningRequestAdapterChain::adaptAndPlan(std::shared_ptr<planning_interface::PlannerManager> const&, std::shared_ptr<planning_scene::PlanningScene const> const&, moveit_msgs::MotionPlanRequest_<std::allocator<void> > const&, planning_interface::MotionPlanResponse&, std::vector<unsigned long, std::allocator<unsigned long> >&) const () from /opt/ros/noetic/lib/libmoveit_planning_request_adapter.so.1.1.16
#13 0x00007de5aaee459a in planning_pipeline::PlanningPipeline::generatePlan(std::shared_ptr<planning_scene::PlanningScene const> const&, moveit_msgs::MotionPlanRequest_<std::allocator<void> > const&, planning_interface::MotionPlanResponse&, std::vector<unsigned long, std::allocator<unsigned long> >&) const ()
   from /opt/ros/noetic/lib/libmoveit_planning_pipeline.so.1.1.16
#14 0x00007de5aaee5d83 in planning_pipeline::PlanningPipeline::generatePlan(std::shared_ptr<planning_scene::PlanningScene const> const&, moveit_msgs::MotionPlanRequest_<std::allocator<void> > const&, planning_interface::MotionPlanResponse&) const () from /opt/ros/noetic/lib/libmoveit_planning_pipeline.so.1.1.16
#15 0x00007de59bf22fdf in pilz_industrial_motion_planner::CommandListManager::solveSequenceItems(std::shared_ptr<planning_scene::PlanningScene const> const&, std::shared_ptr<planning_pipeline::PlanningPipeline> const&, moveit_msgs::MotionSequenceRequest_<std::allocator<void> > const&) const () from /opt/ros/noetic/lib/libsequence_capability.so
--Type <RET> for more, q to quit, c to continue without paging--
#16 0x00007de59bf2377d in pilz_industrial_motion_planner::CommandListManager::solve(std::shared_ptr<planning_scene::PlanningScene const> const&, std::shared_ptr<planning_pipeline::PlanningPipeline> const&, moveit_msgs::MotionSequenceRequest_<std::allocator<void> > const&) () from /opt/ros/noetic/lib/libsequence_capability.so
#17 0x00007de59bf18a76 in pilz_industrial_motion_planner::MoveGroupSequenceService::plan(moveit_msgs::GetMotionSequenceRequest_<std::allocator<void> >&, moveit_msgs::GetMotionSequenceResponse_<std::allocator<void> >&) () from /opt/ros/noetic/lib/libsequence_capability.so
#18 0x00007de59bf1c917 in ros::ServiceCallbackHelperT<ros::ServiceSpec<moveit_msgs::GetMotionSequenceRequest_<std::allocator<void> >, moveit_msgs::GetMotionSequenceResponse_<std::allocator<void> > > >::call(ros::ServiceCallbackHelperCallParams&) () from /opt/ros/noetic/lib/libsequence_capability.so
#19 0x00007de5ab4d7429 in ros::ServiceCallback::call() () from /opt/ros/noetic/lib/libroscpp.so
#20 0x00007de5ab528162 in ros::CallbackQueue::callOneCB(ros::CallbackQueue::TLS*) () from /opt/ros/noetic/lib/libroscpp.so
#21 0x00007de5ab529873 in ros::CallbackQueue::callAvailable(ros::WallDuration) () from /opt/ros/noetic/lib/libroscpp.so
#22 0x00007de5ab57c37e in ros::AsyncSpinnerImpl::threadFunc() () from /opt/ros/noetic/lib/libroscpp.so
#23 0x00007de5aa8e743b in ?? () from /lib/x86_64-linux-gnu/libboost_thread.so.1.71.0
#24 0x00007de5ab407609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#25 0x00007de5ab055353 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) 
```

**Comment by rhaschke** [comment]
> The workflow seems to require that `plan.planning_scene_` be modified with `diff(scene_diff)` but still updated by the planning scene monitor.

Do you know where/how these PSM updates are used?

**Comment by rr-mark** [comment]
> Do you know where/how these PSM updates are used?

If I'm honest, I don't completely follow what `plan_execution.cpp` is doing. But passing a copy of the planning scene around rather than using `plan.planning_scene_` broke a lot of tests.

My best guess is that `planAndExecute` is relying on `plan.planning_scene_` updating to track execution progress, so freezing it via `copyPlanningScene` breaks things. But this is only a guess.

**Comment by rhaschke** [comment]
Could you pick an exemplary test and report its error output here?

**Comment by rr-mark** [comment]
> Could you pick an exemplary test and report its error output here?

https://github.com/moveit/moveit/actions/runs/12993254139/job/36235033434 fails with

```
 [moveit_ros_planning_interface.rosunit-move_group_pick_place_test/PickPlaceTest][FAILURE]
  /home/runner/work/moveit/moveit/.work/target_ws/src/moveit/moveit_ros/planning_interface/test/move_group_pick_place_test.cpp:222
  Expected equality of these values:
    move_group_->pick("object", grasps)
      Which is: MOTION_PLAN_INVALIDATED_BY_ENVIRONMENT_CHANGE
    moveit::core::MoveItErrorCode::SUCCESS
      Which is: 1
  --------------------------------------------------------------------------------
  
  
  SUMMARY
   * RESULT: FAIL
   * TESTS: 1
   * ERRORS: 0
   * FAILURES: 1
```

**Comment by v4hn** [comment]
> [ INFO] [1737995257.355626854]: Found a contact between 'object' (type 'Object') and 'object' (type 'Robot attached'), which constitutes a collision. Contact information is not stored.

This is a classic error when the scene used for checking is not updated during attaching an object.

> My best guess is that planAndExecute is relying on plan.planning_scene_ updating, to track execution progress, so freezing it via copyPlanningScene breaks things. But this is only a guess.

Exactly. c17471549956ec9e1fdf7a27b63734dc4d6f1716

File: moveit_ros/planning/plan_execution/include/moveit/plan_execution/plan_representation.h [hunk 4]
```diff
@@ -82,6 +82,12 @@ struct ExecutableMotionPlan
 
   /// An error code reflecting what went wrong (if anything)
   moveit_msgs::MoveItErrorCodes error_code_;
+
+  planning_scene::PlanningScenePtr copyPlanningScene()
+  {
+    planning_scene_monitor::LockedPlanningSceneRO ls(planning_scene_monitor_);
+    return planning_scene_->diff();
```
Comment (v4hn) [inline moveit_ros/planning/plan_execution/include/moveit/plan_execution/plan_representation.h:89]: This is no copy yet!

```suggestion
    planning_scene::PlanningScenePtr copy = planning_scene_->diff();
    copy.decoupleParent();
    return copy;
```

Comment (rr-mark) [reply moveit_ros/planning/plan_execution/include/moveit/plan_execution/plan_representation.h]: I was wondering if this was needed. I've replaced the `diff` calls with `clone`, as that seems to do the right thing.

**Comment by rr-mark** [comment]
Replacing the `diff` calls with `clone` fixes all the problems I've been seeing in my tests.

From my end, this now works as intended.

I'd rather not dive back into plan_execution.cpp: I don't think I understand the stack well enough to make changes without breaking things. I also get the impression it only locks the planning scene monitor briefly anyway.

**Comment by rr-mark** [comment]
@rhaschke @v4hn could I ask you to re-review this, so I can port it to Moveit2?

@rhaschke are you happy with my changes to `SingleUnlock`, or could you suggest how you want me to change it?

**Review by rhaschke — APPROVED** [review]
LGTM. I reverted the change of visibility for `SingleUnlock`.

**Comment by rr-mark** [comment]
@v4hn could you re-review this when you get a moment?

File: moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp [hunk 5]
```diff
@@ -181,6 +181,17 @@ PlanningSceneMonitor::~PlanningSceneMonitor()
   rm_loader_.reset();
 }
 
+planning_scene::PlanningScenePtr PlanningSceneMonitor::copyPlanningScene(const moveit_msgs::PlanningScene& diff)
+{
+  lockSceneRead();  // We cannot use LockedPlanningSceneRO as this requires a PSMPtr
+  planning_scene::PlanningScenePtr scene = planning_scene::PlanningScene::clone(getPlanningScene());
+  unlockSceneRead();
```
Comment (v4hn) [inline moveit_ros/planning/planning_scene_monitor/src/planning_scene_monitor.cpp:188]:
```suggestion
  // We cannot use LockedPlanningSceneRO for RAII because it requires a PSMPtr
  // Instead assume clone will not throw
  lockSceneRead();
  planning_scene::PlanningScenePtr scene = planning_scene::PlanningScene::clone(getPlanningScene());
  unlockSceneRead();
```

**Review by v4hn — APPROVED** [review]
thanks for the polite ping. :1st_place_medal: 

This patch looks good and adds a use-case that was never considered before.
I commented with some nits, mainly about reducing future confusion.
Could you please rebase the branch, and optionally address the comments?
Assuming CI still passes then, I approve.
